inherit_from: "configs/mono/replica/base_config.yaml"
Dataset:
  type: 'replica'
  dataset_path: "/datasets/replica/office0_cali_const"
  intrinsic_filename: "intrinsics.txt" # path = dataset_path + '/' + intrinsic_file 
  single_thread: True
  Calibration:
    fx: 600.0
    fy: 600.0
    cx: 399.5
    cy: 299.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 800
    height: 600
    depth_scale: 6553.5
    distorted: False
  grad_mask_row: 32
  grad_mask_col: 32
Training:
  edge_threshold: 3.2
