inherit_from: "configs/mono/replica_origin/base_config.yaml"
Dataset:
  dataset_path: "/datasets/replica_origin/office0"
  type: 'replica'
  single_thread: False
  Calibration:
    fx: 600.0
    fy: 600.0
    cx: 599.5
    cy: 339.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1200
    height: 680
    depth_scale: 6553.5
    distorted: False
  grad_mask_row: 32
  grad_mask_col: 32
Training:
  edge_threshold: 4
  after_mapping_itr_num: 20